#!/usr/bin/env python3
"""Generate vectors.h for pilot-nec-decode (two back-to-back NEC frames).

Timing model (demo 27, SysTick=10000, i.e. one IR_RX_NEC() call per 100us):
  falling-edge SampleTime = samples since the previous falling edge
    = low-span + high-span of one pulse pair.

  SYNC  : low 9.0ms + high 4.5ms  -> 90 low + 45 high  = 135  (in [97,150), >=123)
  bit 0 : low 0.6ms + high 0.5ms  ->  6 low +  5 high  = 11   (< 16)
  bit 1 : low 0.6ms + high 1.7ms  ->  6 low + 17 high  = 23   (>= 16)
  trailer: one more falling edge consumes the 32nd bit.

Frame layout (NEC, LSB first per byte): AddressH, AddressL, data, ~data.
Expected decode results are derived from the kernel source and cross-checked
against Oracle-A before being frozen into wrapper.c:
  frame1 0x12/0x34/0xB5 -> UserCode=0x3412 IR_code=0xB5 (see kernel README:
  UserCode = (IR_UserH<<8)+IR_UserL with IR_UserH=AddressL at frame end)
  frame2 0xFF/0x00/0x5A -> UserCode=0x00FF IR_code=0x5A
"""

import sys

def bits_lsb(byte):
    return [(byte >> i) & 1 for i in range(8)]

def frame(ah, al, data):
    s = []
    s += [0] * 90 + [1] * 45                    # sync
    nd = (~data) & 0xFF
    for by in (ah, al, data, nd):
        for b in bits_lsb(by):
            s += [0] * 6 + ([1] * 17 if b else [1] * 5)
    s += [0] * 6 + [1] * 5                      # trailer edge
    return s

def main(out_path):
    samples = [1, 1, 1]                         # establish temp=1 (idle high)
    samples += frame(0x12, 0x34, 0xB5)
    # Inter-frame idle: without it, the first falling edge of frame 2's SYNC
    # reads SampleTime = (trailer 10) + 1 = 11 (not >= SYNC_MIN 97), so it is
    # dropped silently, IR_SampleCnt restarts mid-SYNC and every following
    # pulse lands one edge late -> /data check fails and no frame 2 output.
    # 160 ticks of idle make that edge read 160+90=250 > SYNC_MAX 150: it is
    # discarded as an error edge, the counter restarts clean, and frame 2's
    # SYNC is measured correctly by the next edge (89+45+1=135).
    samples += [1] * 160
    samples += frame(0xFF, 0x00, 0x5A)
    n = len(samples)
    lines = []
    for i in range(0, n, 16):
        lines.append("    " + ",".join("0x%02X" % b for b in samples[i:i+16]) + ",")
    body = "\n".join(lines)
    text = (
        "/* vectors.h for pilot-nec-decode -- GENERATED by gen-vectors.py,\n"
        " * do not edit by hand.  %d samples, two NEC frames:\n"
        " *   frame1: AddressH=0x12 AddressL=0x34 data=0xB5 ~data=0x4A\n"
        " *   frame2: AddressH=0xFF AddressL=0x00 data=0x5A ~data=0xA5\n"
        " * One element == one 100us tick; value is the IR input level.\n"
        " * Included by wrapper.c (SDCC) and host-main.c (gcc) only; it is\n"
        " * test stimulus, not part of the kernel under test.  The runner\n"
        " * pins the CONST area to 0xFC8000 (QEMU 0xFFxxxx data-read quirk,\n"
        " * RESULTS.md).\n"
        " */\n"
        "#define NEC_SAMPLE_COUNT %d\n"
        "static const unsigned char NEC_SAMPLES[NEC_SAMPLE_COUNT] = {\n"
        "%s\n"
        "};\n" % (n, n, body)
    )
    with open(out_path, "w") as f:
        f.write(text)
    print("wrote %s: %d samples" % (out_path, n))

if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "vectors.h")
