#!/usr/bin/env bash
# build.sh - X4 e2e byte chain: official source shapes -> llc ELF objects ->
# mcs251-lld (new CRT with the XDATA_INIT walker) -> byte assertions ->
# QEMU run.
#
# Proven chain shape (uartdemo-33m / rt-acceptance precedents):
#   clang --target=mcs251-unknown-none -std=c11 [-fmcs251-keil]
#         -Xclang -mcs251-memory-contract=1,1,32,8,1 -S -emit-llvm
#   llc -mtriple=mcs251 -mcs251-memory-contract=1,1,32,8,1
#       -mcs251-object-format=elf -filetype=obj
#   mcs251-lld crt.o <objs> --area-start=... --map
#   llvm-objcopy -O ihex
#
# The 1,1,32,8,1 numeric contract is the compatibility layout (TransportVersion
# 1 / ASLayoutVersion 1 / AS0 32-bit / InternalExtended / ExecutionContract 1),
# the proven uartdemo configuration.  Under it AS3/AS4 access functions,
# per-object XSEG placement and xdata_init records all emit through the v1 ELF
# object identity.  (The default no-contract layout is v2-shaped and the X3-R1
# gate rejects AS3/AS4 pointer operands at ELF object output - see README.md
# boundaries.)
#
# Usage: build.sh [--no-qemu]
# Environment overrides: CLANG, LLC, LLD, OBJCOPY, YAML2OBJ, QEMU.
set -euo pipefail

ROOT=$(cd -- "$(dirname -- "$0")" && pwd)
REPO="$ROOT/../.."
OUT="$ROOT/build"
SRC="$ROOT/src"

CLANG=${CLANG:-/home/liu/build-mcs251-s1/bin/clang}
LLC=${LLC:-/home/liu/build-mcs251/bin/llc}
LLD=${LLD:-/home/liu/build-mcs251-lld/bin/lld}
OBJCOPY=${OBJCOPY:-/home/liu/build-mcs251-s1/bin/llvm-objcopy}
YAML2OBJ=${YAML2OBJ:-/home/liu/build-mcs251-lld/bin/yaml2obj}
QEMU=${QEMU:-/home/liu/build-qemu/qemu-system-mcs251}
MACHINE=stc32g144k246

CONTRACT=1,1,32,8,1
DIALECT_INC="$REPO/validation/mcs251-dialect/include"
CRT_YAML="$REPO/validation/mcs251-elf/runtime/crt-selfstart.yaml"

# Link window (rt-acceptance board parameters + the X4 XDATA areas):
#   XSEG at 0x010000 matches the QEMU stc32g XRAM base (stc32g.h
#   STC32G_XDATA_BASE); XDATA_INIT is a CODE-class area like XINIT.
AREA_ARGS=(
  --area-start=HOME=0xff0000 --area-start=VECS=0xff0003
  --area-start=BOOT=0xff0100 --area-start=CSEG=0xff0200
  --area-start=XINIT=0xff8000 --area-start=XDATA_INIT=0xff9000
  --area-start=XSEG=0x010000 --edata-end 0x3fff
)

rm -rf -- "$OUT"
mkdir -p -- "$OUT"

compile() { # name src cflags...
  local name=$1 src=$2; shift 2
  "$CLANG" --target=mcs251-unknown-none -std=c11 -O0 -Wall -Wextra -Werror \
    -I"$SRC" -I"$DIALECT_INC" \
    -Xclang -mcs251-memory-contract="$CONTRACT" \
    -S -emit-llvm "$@" "$src" -o "$OUT/$name.ll"
  "$LLC" -mtriple=mcs251 -mcs251-memory-contract="$CONTRACT" \
    -mcs251-object-format=elf -filetype=obj "$OUT/$name.ll" -o "$OUT/$name.o"
}

# 1) compile the matrix: keil dialect + modern qualifiers (+ the QEMU fw).
compile keil-form "$SRC/keil-form.c" -fmcs251-keil
compile keil-extern "$SRC/keil-extern.c" -fmcs251-keil
compile modern-form "$SRC/modern-form.c"
compile modern-extern "$SRC/modern-extern.c"
compile qemu-fw "$SRC/qemu-fw.c" -fmcs251-keil
compile qemu-ext "$SRC/qemu-ext.c" -fmcs251-keil
compile stub-main "$SRC/stub-main.c"

# X2-defect reproducer (kept at -O2 on purpose; see src/defect-repro.c and
# the README's X2-defect section).  The X2 glue fix landed: this object now
# pins the GREEN -O2 shape (each MOVX preceded by its own DPXL/DPL/DPH
# lane writes), asserted by check-bytes.py.  The -O0 images above remain
# the byte-stable baseline mirrors.
"$CLANG" --target=mcs251-unknown-none -std=c11 -O2 -Wall -Wextra -Werror \
  -I"$SRC" -Xclang -mcs251-memory-contract="$CONTRACT" \
  -S -emit-llvm "$SRC/defect-repro.c" -o "$OUT/defect-repro.ll"
"$LLC" -mtriple=mcs251 -mcs251-memory-contract="$CONTRACT" \
  -mcs251-object-format=elf -filetype=obj "$OUT/defect-repro.ll" \
  -o "$OUT/defect-repro.o"

# 2) CRT: the X4-extended pure-ELF fixture (yaml2obj; the in-tree crt.o is
#    the same artifact, regenerated by gen-crt-elf.sh).
"$YAML2OBJ" "$CRT_YAML" -o "$OUT/crt.o"

# 3) link: byte-chain image + modern image + QEMU firmware image.
link_img() { # out objs...
  local out=$1; shift
  "$LLD" -flavor mcs251 "${AREA_ARGS[@]}" --keep-symbols \
    --map="$OUT/$out.map" -o "$OUT/$out.elf" "$@" "$OUT/crt.o"
}
link_img keil "$OUT/keil-form.o" "$OUT/keil-extern.o" "$OUT/stub-main.o"
link_img modern "$OUT/modern-form.o" "$OUT/modern-extern.o" "$OUT/stub-main.o"
link_img fw "$OUT/qemu-fw.o" "$OUT/qemu-ext.o"
link_img defect-o2 "$OUT/defect-repro.o" "$OUT/stub-main.o"

"$OBJCOPY" -O ihex "$OUT/fw.elf" "$OUT/fw.hex"

# 4) byte-level assertions (XSEG addresses, DPXL-before-MOVX sequences,
#    xdata_init record contents, CODE image bytes, map boundary symbols).
python3 "$ROOT/check-bytes.py" "$OUT"

# 5) QEMU run (skipped with --no-qemu or when the binary is missing).
if [ "${1:-}" = "--no-qemu" ]; then
  echo "QEMU run skipped (--no-qemu); byte chain verified in $OUT"
  exit 0
fi
command -v "$QEMU" >/dev/null || { echo "qemu missing: $QEMU" >&2; exit 1; }

# Poison the clear-only object before reset. QEMU RAM starts at zero, so
# without this a walker that skips its zero loop still prints OK2/PASS.
# Derive its range from the map rather than baking in the current layout.
python3 - "$OUT/fw.map" > "$OUT/fw.poison-addrs" <<'PY'
import sys
from pathlib import Path
rows = [line.split() for line in Path(sys.argv[1]).read_text().splitlines()
        if ':.mcs251.XSEG._fwzero ' in line]
assert len(rows) == 1, 'expected one fwzero XSEG slice'
_, start, size = rows[0]
start, size = int(start, 16), int(size[1:], 16)
assert size == 32 and 0x010000 <= start < start + size <= 0x020000
for addr in range(start, start + size):
    print(hex(addr))
PY
POISON_ARGS=()
while IFS= read -r addr; do
  POISON_ARGS+=(-device "loader,addr=$addr,data=0xa7,data-len=1")
done < "$OUT/fw.poison-addrs"

SERIAL="$OUT/fw.serial"
: > "$SERIAL"
( for _ in $(seq 1 120); do
    if [ -s "$SERIAL" ] && tail -c 256 "$SERIAL" | grep -q "XDATA-E2E-"; then
      pkill -TERM -f "qemu-system-mcs251.*fw.hex" 2>/dev/null
      exit 0
    fi
    sleep 0.5
  done ) &
WATCHER=$!
timeout --foreground 60 "$QEMU" -M "$MACHINE" -bios "$OUT/fw.hex" \
  "${POISON_ARGS[@]}" -accel tcg -display none -monitor none -serial "file:$SERIAL" \
  > "$OUT/fw.qemu.stdout" 2> "$OUT/fw.qemu.stderr" || true
kill "$WATCHER" 2>/dev/null || true
wait "$WATCHER" 2>/dev/null || true

echo "== QEMU serial transcript =="
cat "$SERIAL"
if tail -n 1 "$SERIAL" | grep -q '^XDATA-E2E-PASS$'; then
  echo "X4 e2e: PASS (byte chain + QEMU)"
else
  echo "X4 e2e: QEMU FAIL (see $SERIAL)" >&2
  exit 1
fi
