#!/usr/bin/env python3
"""Generate the shared NOP sleds used by the TFPU latency scan.

The TFPU completion mechanism is undocumented, so we measure it directly:
trigger a command, burn exactly `n` CPU clocks of NOPs, snapshot R4..R7, and
report the first `n` at which the result equals the IEEE-754 expectation.

WHY A SHARED SLED
`JMP @A+DPTR` sets PC[15:0] = A + DPTR (upper PC bits retained) and A is only
8 bits wide, so a contiguous range of entry points must fit inside 256 bytes.
Rather than unroll one body per n, a single run of TPU_SLED NOPs is entered
partway down:

    PC = sled + (TPU_SLED - n)

The dispatcher in tfpu-probe.asm picks DPTR/A so that A + DPTR lands there:

    n = 0..255  (lo):  DPTR = sled + TPU_SLED_LO,  A = 255 - n
    n > 255     (hi):  DPTR = sled,                A = TPU_SLED - n

With TPU_SLED = 272 that covers n = 0..272, which spans the manual's worst case
(sin/cos 32..270 clocks), at ~272 bytes per command instead of tens of
kilobytes.  Every n shares one snapshot body; n lives entirely in A.

Usage: python3 gen-sled.py > sled.inc
"""

SLED = 272
# lo-range DPTR base: entering at sled + TPU_SLED_LO with A = 255 gives n = 0,
# i.e. PC = sled + TPU_SLED_LO + 255 = sled + TPU_SLED - 0.
SLED_LO = SLED - 255


def emit(name):
    out = []
    out.append("; ---- %s: %d NOPs, entry offset = %d - n ----" % (name, SLED, SLED))
    out.append("_tpu_%s_sled:" % name)
    out.append("        .rept %d" % SLED)
    out.append("        nop")
    out.append("        .endm")
    out.append("_tpu_%s_snap:" % name)
    out.append("        mov S_L4,r4")
    out.append("        mov S_L5,r5")
    out.append("        mov S_L6,r6")
    out.append("        mov S_L7,r7")
    out.append("        ljmp _tpu_%s_done" % name)
    return out


def main():
    lines = ["; AUTO-GENERATED by gen-sled.py -- do not edit by hand.",
             "; TPU_SLED = NOP count; TPU_SLED_LO = lo-range DPTR offset.",
             "TPU_SLED = %d" % SLED,
             "TPU_SLED_LO = %d" % SLED_LO]
    for name in ("mul", "add", "sin"):
        lines += emit(name)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
